version: "3.6"

services:
  tg_bot:
    restart: unless-stopped
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
    env_file:
      - ./bot/.env
    volumes:
      - ./bot/:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

