FROM python:3.10

WORKDIR /app

RUN pip install "poetry==1.4.2"
COPY poetry.lock pyproject.toml ./

RUN poetry config installer.max-workers 4 && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-ansi
CMD ["python", "main.py"]
